swagger: '2.0'
info:
  $ref: ./info.yaml

basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json

paths:
  $ref: ./paths/__init__.yaml

securityDefinitions:
  $ref: ./securityDefinitions/__init__.yaml

definitions:
  $ref: ./definitions/__init__.yaml

responses:
  $ref: ./responses/__init__.yaml

tags:
  $ref: ./tags.yaml