dbConnection:
  host: 127.0.0.1
  user: yourUser
  password: yourPassword
  database: drones
server:
  host: 0.0.0.0
  port: 5000
  swaggerDocsPrefix: /
  admin:
    name: Master Admin
    password: "admin"
    email: "master.admin@local.host"
jwt:
  keys:
    folder: "keys/"
    private: "id_rsa"
    public: "id_rsa.pub"
  expiration:
    access: "2h" # 2 hours: 1000 * 60 * 60 * 2
    refresh: 15811200000 # half of year: 1000 * 60 * 60 * 24 * (366 / 2)
  issuer: SuperAdmin
  refreshLength: 128

cors:
  whitelist:
  - localhost:5000
  - localhost:3000
  - localhost:4200
  methods:
  - GET
  - POST
  - DELETE
  - PUT
  - PATCH
